# API Gateway Server Configuration
server:
  port: 9080
  servlet:
    context-path: /

app-jws:
  jwk-cache-lifespan: 600000
  jwk-refresh-time: 60000
  jwk-url: http://localhost:9083/jws-service/.well-known/jwks.json
  connect-timeout: 5000
  read-timeout: 5000



spring:
  application:
    name: api-gateway-server
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: demo-service
              uri: http://localhost:9081/
              predicates:
                - Path=/demo-service/demo
              filters:
                - name: JwtValidationFilter
                  args:
                    tokenHeaderName: x-auth-user
                    removeHeaders:
                      - x-auth-user
                      - postman-token
                    claimToHeaderMap:
                      userId: x-user-id
                      deviceId: x-device-id
            - id: demo-service-aggregation
              uri: http://localhost:9081/
              predicates:
                - Path=/demo-service/aggregation
              filters:
                - name: AggregatorFilter
                  args:
                    serviceUrls:
                      - http://localhost:9081/demo-service/aggregator/service
                      - http://localhost:9081/demo-service/aggregator/service1
                      - http://localhost:9082/test-service/test
            - id: test-service
              uri: http://localhost:9082/
              predicates:
                - Path=/test-service/**